### ISSUE TITLE
請問一下，找不到$USER/Library/Services/ 資料夾～

### ISSUE THREAD

**Issue by derekypp** [pilisir/macOS_merge_copy#1]
我是Catalina　10.15.4

**Comment by pilisir** [comment]
Hi @derekypp

$USER 是變數，指的是這部 mac 的使用者
Library 在繁體中文的 Finder 下，叫做"資源庫"，是個隱藏資料夾
你可以在使用 Finder 時，輸入 `⇧` + `⌘` + `.` 切換是否顯示隱藏文件

**Comment by derekypp** [comment]
已經找到資料夾了，感謝
------------------------------

但是我用了選了一個資料夾，按了服務裡面 Merge Copy

再到我想去資料夾上面準備【貼上】，但發現不能貼上
感覺上是沒有做COPY這個動作

**Comment by pilisir** [comment]
Hi @derekypp

> 但是我用了選了一個資料夾，按了服務裡面 Merge Copy
請問你點擊後服務的 Merge Copy 後，是否要另外跳出新的 Finder 視窗？
